baseURL = 'https://87188202.xyz'  
languageCode = 'zh-cn'
title = 'Myblogs'
theme = './themes/PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true